# Generated by Django 4.2 on 2023-05-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_statuspost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusPost',
        ),
    ]
