# Generated by Django 4.2 on 2023-05-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_statuspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='art_name',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
